config/routes.rb
Rails.application.routes.draw do
  resources :restaurants

  devise_for :users

  root 'pages#home'
  resources :pages
  get 'map' => 'pages#map'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
		
	end	

	def map
		
	end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params[:restaurant]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/_navbar.html.erb
<div class="navbar-wrapper">
  <div class="navcontainer">
    <div class="navbar navbar-default navbar-fixed-top effect1" role="navigation" style="border-bottom:none; background-color:#ffffff; border-top: 4px solid crimson; -webkit-box-shadow: 0px 5px 9px 0px rgba(50, 50, 50, 0.75);
-moz-box-shadow:    0px 5px 9px 0px rgba(50, 50, 50, 0.75);
box-shadow:         0px 5px 9px 0px rgba(50, 50, 50, 0.75);">
      <ul class="nav navbar-nav pull-right" style="font-family: 'Montserrat', sans-serif;font-weight: 400; color: white;padding-top: 3.3px;">
            <% if user_signed_in? %>
            <li><%= button_to "Sign Out", destroy_user_session_path, :method => "delete", class: "btn btn-primary", style: "margin-right: 11px;"%></li>
            <% else %>  
              <li class="float: right"><form action="/users/sign_in/"><input type="submit" value="Log In" class="btn btn-info" style="margin-right: 11px; float: right"></form></li>
            <% end %>  
          </ul>
        <div class="navbar-header">
          <a class="navbar-brand" href="#" style="font-family: 'Montserrat', sans-serif;color: crimson;font-size: xx-large;font-weight: 700;padding-top: 17px;">FoodMob</a>
        </div>
         
          

    </div>

  </div><!-- /container -->
</div><!-- /navbar wrapper -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foodmob</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/navbar" %>

<%= yield %>


</body>
</html>

app/views/pages/home.html.erb
<style>
.carousel .item {-webkit-transition: opacity 3s; -moz-transition: opacity 3s; -ms-transition: opacity 3s; -o-transition: opacity 3s; transition: opacity 3s;}
.carousel .active.left {left:0;opacity:0;z-index:2;}
.carousel .next {left:0;opacity:1;z-index:1;}

  .collapse {
    display: none !important;
  }

  .btn-outlined.btn-warning {
      background: none;
      border: 3px solid #f0ad4e;
      color: #f0ad4e;
  }
  .btn-outlined.btn-warning:hover,
  .btn-outlined.btn-warning:active {
      color: #FFF;
      background: #ed9c28;
  }

  .btn-outlined.btn-danger {
      background: none;
  border: 8px solid #d9534f;
  color: inherit;
  font-size: inherit;
  }
  .btn-outlined.btn-danger:hover,
  .btn-outlined.btn-danger:active {
      color: #FFF;
      background: #d2322d;
  }

  .carousel-inner > .item > img, .carousel-inner > .item > a > img {
  line-height: 1;
  -webkit-filter: contrast(95%);
  }

      html, body, #map-canvas {
        height: 100%;
        margin: 0px;
        padding: 0px
      }
      .controls {
        margin-top: 16px;
        border: 1px solid transparent;
        border-radius: 2px 0 0 2px;
        box-sizing: border-box;
        -moz-box-sizing: border-box;
        height: 32px;
        outline: none;
        box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);
      }

      #pac-input {
        background-color: #fff;
        padding: 0 11px 0 13px;
        width: 400px;
        font-family: Roboto;
        font-size: 15px;
        font-weight: 300;
        text-overflow: ellipsis;
      }

      #pac-input:focus {
        border-color: #4d90fe;
        margin-left: -1px;
        padding-left: 14px;  /* Regular padding-left + 1. */
        width: 401px;
      }

      .pac-container {
        font-family: Roboto;
      }

      #type-selector {
        color: #fff;
        background-color: #4d90fe;
        padding: 5px 11px 0px 11px;
      }

      #type-selector label {
        font-family: Roboto;
        font-size: 13px;
        font-weight: 300;
      }
  }
</style>




<!-- Carousel
================================================== -->
<div id="myCarousel" class="carousel slide" style="margin-bottom: 0px;">
  <!-- Indicators -->
  <ol class="carousel-indicators" style="z-index: 1">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="item active">
      <img src="/images/table.jpg" class="img-responsive">
      <div class="container">
        <div class="carousel-caption" style="z-index: 1;: 800; height: 171px;">
          <h1 style="font-family: 'Montserrat', sans-serif; font-weight: 700 ">Your Favorite Restaurants Delivered to You.</h1>
          <p id="ordersize" style="font-family: 'Montserrat', sans-serif; font-weight: 700; text-shadow: 3px 2px 2px #000;">No minimum order size - First delivery is free.</p>
          <p><a class="btn btn-outlined btn-danger" href="http://getbootstrap.com" style="text-shadow: 3px 2px 2px #000;font-family: 'Montserrat', sans-serif; font-weight: 700;">Sign Up</a></p>
        </div>
      </div>
    </div>
    <div class="item">
      <img src="/images/pizzapull.jpg" class="img-responsive">
      <div class="container">
        <div class="carousel-caption" style="z-index: 1; height: 171px;bottom: 54px;">
          <h1 style="font-family: 'Montserrat', sans-serif; font-weight: 700; padding-top: 101px;">Serving West Hollywood and Beverly Hills </h1>
          <p style="font-family: 'Montserrat', sans-serif; font-weight: 700; text-shadow: 3px 2px 2px #000;">Your favorite foods in 45 minutes or less.</p>
          <p><a class="btn btn-outlined btn-danger" href="http://getbootstrap.com" style="text-shadow: 3px 2px 2px #000; font-family: 'Montserrat', sans-serif; font-weight: 700;">Sign Up</a></p>
        </div>
      </div>
    </div>
    <div class="item">
      <img src="/images/thai.jpg" class="img-responsive">
      <div class="container">
        <div class="carousel-caption" style="z-index: 1; height: 120px;bottom: 20px;">
          <h1 style="font-family: 'Montserrat', sans-serif; font-weight: 700; text-shadow: 3px 2px 2px #000;">Order Online and have your food within 45 minutes.</h1>
          <p style="font-family: 'Montserrat', sans-serif; font-weight: 700; text-shadow: 3px 2px 2px #000;"></p>







          <p><a class="btn btn-outlined btn-danger" href="http://getbootstrap.com" style="font-family: 'Montserrat', sans-serif; font-weight: 700; color: crimson;">Sign Up</a></p>
        </div>
      </div>
    </div>
  </div>
  <!-- Controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="icon-prev"></span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="icon-next"></span>
  </a>  
</div>
<!-- /.carousel -->

<div class="container" style="background-color: #faf8ed">
  <p style="font-family: 'Montserrat', sans-serif; font-weight: 700;"> "We deliver from the best restaurants."</p>

  <iframe src="https://mapsengine.google.com/map/embed?mid=zX6GIp8byws8.kzL25DC8CRKU" width="100%" height="480"></iframe>
</div>  





<!-- Marketing messaging and featurettes
================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->

<div class="container" style="padding-top:18px;">

  <div class="container marketing" style="background-color: #ffffff; width: 100%; position: relative; padding-top: 11px;">
      <h1 style="font-family: 'Montserrat', sans-serif; font-weight: 700; color: crimson;">What our clients are saying:</h1>

    <!-- Three columns of text below the carousel -->
    <div class="row">
      <div class="col-md-4 text-center">
        <img class="img-circle" src="/images/carla.jpg">
        <p>"Extremely pleased with Claudia. I would recommend her to my friends and family! I am looking forward to a continued great working relationship with claudia."</p>
        <p><a class="btn btn-default" href="#">View details »</a></p>
      </div>
      <div class="col-md-4 text-center">
        <img class="img-circle" src="images/smiles.jpg/">
        <p>"They were amazing! Our apartment was a mess and they stayed even longer than planned, making sure everything was spotless! We were so impressed with their work ethic and how nice they were too. I highly recommend them!"</p>
        <p><a class="btn btn-default" href="#">View details »</a></p>
      </div>
      <div class="col-md-4 text-center">
        <img class="img-circle" src="/images/guy1.jpg">
        <p>"Hi. I want to thank you guys so much. My friend let me know about you guys and I am so happy he did. At first I was a bit hesitant to hire a crew of people to come to my house, but the maids were so nice, Thanks guys!!!"

  </p>
        <p><a class="btn btn-default" href="#">View details »</a></p>
      </div>
    </div><!-- /.row -->






    <!-- Three columns of text below the carousel -->
  </div>



    <!-- START THE FEATURETTES -->

    <hr class="featurette-divider">

    <div class="featurette">
      <img class="featurette-image img-circle pull-right" src="http://placehold.it/512">
      <h2 class="featurette-heading">Responsive Design. <span class="text-muted">It'll blow your mind.</span></h2>
      <p class="lead">In simple terms, a responsive web design figures out what resolution of device it's being served on. Flexible grids then size correctly to fit the screen.</p>
    </div>

    <hr class="featurette-divider">

    <div class="featurette">
      <img class="featurette-image img-circle pull-left" src="http://placehold.it/512">
      <h2 class="featurette-heading">Smaller Footprint. <span class="text-muted">Lightweight.</span></h2>
      <p class="lead">The new Bootstrap 3 promises to be a smaller build. The separate Bootstrap base and responsive.css files have now been merged into one. There is no more fixed grid, only fluid.</p>
    </div>

    <hr class="featurette-divider">

    <div class="featurette">
      <img class="featurette-image img-circle pull-right" src="http://placehold.it/512">
      <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Flatness.</span></h2>
      <p class="lead">A big design trend for 2013 is "flat" design. Gone are the days of excessive gradients and shadows. Designers are producing cleaner flat designs, and Bootstrap 3 takes advantage of this minimalist trend.</p>
    </div>

    <hr class="featurette-divider">

</div>

  <!-- /END THE FEATURETTES -->


  <!-- FOOTER -->
  <footer>
    <p class="pull-right"><a href="#">Back to top</a></p>
    <p>This Bootstrap layout is compliments of Bootply. · <a href="http://www.bootply.com/62603">Edit on Bootply.com</a></p>
  </footer>

</div><!-- /.container -->

app/views/pages/map.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Place searches</title>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <style>
      html, body, #map-canvas {
        height: 100%;
        margin: 0px;
        padding: 0px
      }
    </style>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places"></script>
    <script>
var map;
var infowindow;

function initialize() {
  var pyrmont = new google.maps.LatLng(-33.8665433, 151.1956316);

  map = new google.maps.Map(document.getElementById('map-canvas'), {
    center: pyrmont,
    zoom: 15
  });

  var request = {
    location: pyrmont,
    radius: 500,
    types: ['store']
  };
  infowindow = new google.maps.InfoWindow();
  var service = new google.maps.places.PlacesService(map);
  service.nearbySearch(request, callback);
}

function callback(results, status) {
  if (status == google.maps.places.PlacesServiceStatus.OK) {
    for (var i = 0; i < results.length; i++) {
      createMarker(results[i]);
    }
  }
}

function createMarker(place) {
  var placeLoc = place.geometry.location;
  var marker = new google.maps.Marker({
    map: map,
    position: place.geometry.location
  });

  google.maps.event.addListener(marker, 'click', function() {
    infowindow.setContent(place.name);
    infowindow.open(map, this);
  });
}

google.maps.event.addDomListener(window, 'load', initialize);

    </script>
  </head>
  <body>
    <div id="map-canvas"></div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>Listing restaurants</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>